#oxtalks:
#  hostname: localhost:3000
#  username: richard.hills@gmail.com
#  password: richard
oxtalks:
  hostname: talks-ox-test.nsms.ox.ac.uk
  username: richard.hills@gmail.com
  password: richard
logging_config_filename: ../settings/logging.yml
sources_filename: ../settings/event_sources.yml
